[workspace]
resolver = "2"
members = [
    "crates/osnip-core",
    "crates/osnip-daemon",
    "crates/osnip-cli",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
repository = "https://github.com/franciscogranda/Osnip"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "process", "time", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
libwayshot = "0.7"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "bmp", "webp"] }
iced = { version = "0.14", default-features = false, features = ["image", "tokio", "wayland", "wgpu"] }
toml = "0.8"
dirs = "5"
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[profile.release]
lto = "thin"
codegen-units = 1
